// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Job documents
 */
interface JobDocumentData {
  /**
   * Company Logo field in *Job*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: job.company_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Job Title field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Company Name field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Job Description field in *Job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.job_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_description: prismic.RichTextField;

  /**
   * Date Started field in *Job*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.date_started
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_started: prismic.DateField;

  /**
   * Date Ended field in *Job*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.date_ended
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_ended: prismic.DateField;

  /**
   * Company Link field in *Job*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: job.company_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_link: prismic.LinkField;
}

/**
 * Job document from Prismic
 *
 * - **API ID**: `job`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<JobDocumentData>, "job", Lang>;

type PageDocumentDataSlicesSlice =
  | ProjectArchiveSlice
  | SelfBlurbSlice
  | RichTextSlice
  | SkillsSectionSlice
  | JobHistorySlice
  | FeaturedProjectsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Logo Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.logo_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Title Text field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Lead Text field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.lead_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lead_text: prismic.RichTextField;

  /**
   * Self Blurb field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.self_blurb
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  self_blurb: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Project Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Project Job field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_job
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_job: prismic.ContentRelationshipField<"job">;

  /**
   * Project Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;

  /**
   * year field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * Featured field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Content for Skill documents
 */
interface SkillsDocumentData {
  /**
   * Skill Name field in *Skill*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.skill_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill_name: prismic.KeyTextField;
}

/**
 * Skill document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillsDocumentData>, "skills", Lang>;

export type AllDocumentTypes =
  | JobDocument
  | PageDocument
  | ProjectDocument
  | SkillsDocument;

/**
 * Primary content in *FeaturedProjects → Default → Primary*
 */
export interface FeaturedProjectsSliceDefaultPrimary {
  /**
   * Projects field in *FeaturedProjects → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.default.primary.projects
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projects: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for FeaturedProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProjects*
 */
type FeaturedProjectsSliceVariation = FeaturedProjectsSliceDefault;

/**
 * FeaturedProjects Shared Slice
 *
 * - **API ID**: `featured_projects`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSlice = prismic.SharedSlice<
  "featured_projects",
  FeaturedProjectsSliceVariation
>;

/**
 * Primary content in *JobHistory → Default → Primary*
 */
export interface JobHistorySliceDefaultPrimary {
  /**
   * Resume field in *JobHistory → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: job_history.default.primary.resume
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  resume: prismic.LinkToMediaField;
}

/**
 * Default variation for JobHistory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobHistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobHistorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobHistory*
 */
type JobHistorySliceVariation = JobHistorySliceDefault;

/**
 * JobHistory Shared Slice
 *
 * - **API ID**: `job_history`
 * - **Description**: JobHistory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobHistorySlice = prismic.SharedSlice<
  "job_history",
  JobHistorySliceVariation
>;

/**
 * Default variation for ProjectArchive Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectArchiveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProjectArchive*
 */
type ProjectArchiveSliceVariation = ProjectArchiveSliceDefault;

/**
 * ProjectArchive Shared Slice
 *
 * - **API ID**: `project_archive`
 * - **Description**: ProjectArchive
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectArchiveSlice = prismic.SharedSlice<
  "project_archive",
  ProjectArchiveSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SelfBlurb → Default → Primary*
 */
export interface SelfBlurbSliceDefaultPrimary {
  /**
   * blurb field in *SelfBlurb → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: self_blurb.default.primary.blurb
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blurb: prismic.RichTextField;
}

/**
 * Default variation for SelfBlurb Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelfBlurbSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SelfBlurbSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SelfBlurb*
 */
type SelfBlurbSliceVariation = SelfBlurbSliceDefault;

/**
 * SelfBlurb Shared Slice
 *
 * - **API ID**: `self_blurb`
 * - **Description**: SelfBlurb
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SelfBlurbSlice = prismic.SharedSlice<
  "self_blurb",
  SelfBlurbSliceVariation
>;

/**
 * Default variation for SkillsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SkillsSection*
 */
type SkillsSectionSliceVariation = SkillsSectionSliceDefault;

/**
 * SkillsSection Shared Slice
 *
 * - **API ID**: `skills_section`
 * - **Description**: SkillsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSectionSlice = prismic.SharedSlice<
  "skills_section",
  SkillsSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      JobDocument,
      JobDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      SkillsDocument,
      SkillsDocumentData,
      AllDocumentTypes,
      FeaturedProjectsSlice,
      FeaturedProjectsSliceDefaultPrimary,
      FeaturedProjectsSliceVariation,
      FeaturedProjectsSliceDefault,
      JobHistorySlice,
      JobHistorySliceDefaultPrimary,
      JobHistorySliceVariation,
      JobHistorySliceDefault,
      ProjectArchiveSlice,
      ProjectArchiveSliceVariation,
      ProjectArchiveSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SelfBlurbSlice,
      SelfBlurbSliceDefaultPrimary,
      SelfBlurbSliceVariation,
      SelfBlurbSliceDefault,
      SkillsSectionSlice,
      SkillsSectionSliceVariation,
      SkillsSectionSliceDefault,
    };
  }
}
