// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_projects: dynamic(() => import("./FeaturedProjects")),
  job_history: dynamic(() => import("./JobHistory")),
  rich_text: dynamic(() => import("./RichText")),
  skills_section: dynamic(() => import("./SkillsSection")),
};
